server {
    listen 80;
    listen [::]:80;
    server_name tjcu8.elma-gohan.xyz;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://tjcu8.elma-gohan.xyz$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name tjcu8.elma-gohan.xyz;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/tjcu8.elma-gohan.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tjcu8.elma-gohan.xyz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:Tjcu8TLS:10m;
    ssl_session_tickets off;

    root /var/www/tjcu8/current;
    index index.html;
    charset utf-8;

    access_log /var/log/nginx/tjcu8.access.log;
    error_log /var/log/nginx/tjcu8.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|gif|svg|ico|webp|woff|woff2|eot|ttf)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
